global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

        #  - job_name: 'cadvisor'
        #static_configs:
        #- targets: ['cadvisor:8080']

  - job_name: 'home-assistant'
    metrics_path: '/api/prometheus'
    static_configs:
      - targets: ['homeassistant:8123']
    scheme: http
    basic_auth:
      username: 'mrj'
      password: 'R^VrTjar1uHXty$1c#gs'

rule_files:
  - 'alert.rules'

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']
