name: Self-Hosted Runner Workflow

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: [self-hosted, Linux, label-2]  # Bruger din self-hosted runner
    env:
      MY_VAR: "test-min-variable"

    steps:
      - name: Run a one-line script
        run: echo "Hello, world!"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16.x'

      - name: Echo something
        run: |
          echo something > /tmp/something
          cat /tmp/something

      - name: Print env var
        run: |
          echo $MY_VAR
          echo $MY_VAR >> /tmp/something
